import { Sparkles } from "lucide-react";

function ResumeSummary({
  summary = "AI-powered resume insights will appear here after analysis.",
  strengths = [],
  improvements = [],
}) {
  return (
    <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">

      {/* Header */}

      <div className="flex items-center gap-3">

        <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-50">
          <Sparkles
            size={24}
            className="text-violet-600"
          />
        </div>

        <div>
          <h2 className="text-xl font-semibold text-slate-900">
            AI Resume Insights
          </h2>

          <p className="text-sm text-slate-500">
            Personalized feedback generated by AI.
          </p>
        </div>

      </div>

      {/* Summary */}

      <div className="mt-8 rounded-2xl bg-slate-50 p-5">
        <h3 className="mb-2 font-semibold text-slate-900">
          Professional Summary
        </h3>

        <p className="leading-7 text-slate-600">
          {summary}
        </p>
      </div>

      {/* Strengths */}

      <div className="mt-8">

        <h3 className="mb-3 font-semibold text-green-700">
          Strengths
        </h3>

        {strengths.length > 0 ? (
          <ul className="space-y-2">
            {strengths.map((item) => (
              <li
                key={item}
                className="rounded-xl bg-green-50 p-3 text-green-700"
              >
                ✓ {item}
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-slate-500">
            AI will identify your strongest points here.
          </p>
        )}

      </div>

      {/* Improvements */}

      <div className="mt-8">

        <h3 className="mb-3 font-semibold text-orange-700">
          Suggested Improvements
        </h3>

        {improvements.length > 0 ? (
          <ul className="space-y-2">
            {improvements.map((item) => (
              <li
                key={item}
                className="rounded-xl bg-orange-50 p-3 text-orange-700"
              >
                • {item}
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-slate-500">
            AI suggestions will appear after Gemini analysis.
          </p>
        )}

      </div>

    </div>
  );
}

export default ResumeSummary;